import os

print(os.getcwd())

os.chdir('/Chapter10_File_Exceptions')
print(os.getcwd())
